-- ============================================================================
-- Areas tab follow-up:
--   1) Add input_mode to estimate_area_measurements so a section can be
--      flipped between Length × Width (dimensioned) and direct Total entry
--      (total_only).
--   2) Change estimate_areas.parent_area_id FK from ON DELETE SET NULL to
--      ON DELETE CASCADE so deleting a floor that has nested coves removes
--      those coves with it — matches user expectation when the delete confirm
--      already says "This will also delete its sections".
-- ============================================================================

-- ── 1. input_mode column ──────────────────────────────────────────────────
ALTER TABLE estimate_area_measurements
  ADD COLUMN IF NOT EXISTS input_mode text NOT NULL DEFAULT 'dimensioned'
  CHECK (input_mode IN ('dimensioned', 'total_only'));


-- ── 2. parent_area_id ON DELETE behavior: SET NULL → CASCADE ─────────────
-- The Phase 2 migration declared the column inline so the constraint name
-- was auto-generated by Postgres. Find it dynamically by column rather than
-- assuming the default name; this stays idempotent if a previous run already
-- swapped it.
DO $$
DECLARE
  con_name text;
BEGIN
  SELECT c.conname INTO con_name
  FROM pg_constraint c
  JOIN pg_attribute a
    ON a.attrelid = c.conrelid
   AND a.attnum = ANY (c.conkey)
  WHERE c.conrelid = 'public.estimate_areas'::regclass
    AND c.contype = 'f'
    AND a.attname = 'parent_area_id'
  LIMIT 1;

  IF con_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.estimate_areas DROP CONSTRAINT %I', con_name);
  END IF;

  ALTER TABLE public.estimate_areas
    ADD CONSTRAINT estimate_areas_parent_area_id_fkey
    FOREIGN KEY (parent_area_id)
    REFERENCES public.estimate_areas(id)
    ON DELETE CASCADE;
END $$;
